java_library(
  name = "app",
  visibility = ["//visibility:public"],
  srcs = glob(["*.java"]),
  deps = [
    "//logging/src/main/java/logging",
    "//persistence/src/main/java/persistence",
  ],
)
